// integrations/vuejs/src/GoodDataChart.vue
<script setup lang="ts">
import { onMounted } from 'vue'
import * as React from 'react'
import * as ReactDOM from 'react-dom'
import tigerFactory, { TigerTokenAuthProvider } from '@gooddata/sdk-backend-tiger'
import '@gooddata/sdk-ui-ext/styles/css/main.css'
import { InsightView } from '@gooddata/sdk-ui-ext'

const backend = tigerFactory()
    .onHostname(import.meta.env.VITE_HOSTNAME)
    .withAuthentication(
        new TigerTokenAuthProvider(import.meta.env.VITE_GD_API_TOKEN)
    )

onMounted(() => {
  const node = document.getElementById('gooddata-chart')
  const props = {
    workspace: import.meta.env.VITE_WORKSPACE_ID,
    insight: import.meta.env.VITE_INSIGHT_ID,
    backend
  }

  if (node) {
    ReactDOM.render(React.createElement(InsightView, props), node)
  }
})
</script>

<template>
  <main>
    <h1>Where people buy our fruits?</h1>
    <div id="gooddata-chart"></div>
  </main>
</template>

<style scoped>
#gooddata-chart {
  width: 100%;
  height: 400px;
}
</style>

// integrations/nextjs/src/app/components/GoodDataChart.tsx
"use client";

import {
  tigerFactory,
  TigerTokenAuthProvider,
} from "@gooddata/sdk-backend-tiger";
import { BackendProvider, WorkspaceProvider } from "@gooddata/sdk-ui";
import { InsightView } from "@gooddata/sdk-ui-ext";

export default function GoodDataChart() {
  const backend = tigerFactory()
    .onHostname(process.env.NEXT_PUBLIC_GD_HOSTNAME!)
    .withAuthentication(
      new TigerTokenAuthProvider(process.env.NEXT_PUBLIC_GD_API_TOKEN!)
    );

  return (
    <BackendProvider backend={backend}>
      <div className="gooddata-chart">
        <WorkspaceProvider workspace={process.env.NEXT_PUBLIC_GD_WORKSPACE_ID!}>
          <InsightView insight={process.env.NEXT_PUBLIC_GD_INSIGHT_ID!} />
        </WorkspaceProvider>
      </div>
    </BackendProvider>
  );
}
